### ISSUE TITLE
save to png?

### ISSUE THREAD

**Issue by getarobo** [nicholas477/AsyncReadRT#1]
Hi @nicholas477 

thanks for the awesome plugin!!!!

I have been trying to save TArray<FlinearColor> to a png file but I am failing. I know its off topic here but is my approch wrong?

```
// TArray<FLinearColor> colors <-- I got from UAsyncReadEntireRTAction


// FIRST I first convert to TArray<FColor>
TArray<FColor> fcolors;
for(int i = 0; i < colors.Num(); i++)
{
   FColor a = colors[i].ToFColor(true);
   fcolors.Add(a);
}

// SECOND, i compress it
TArray<uint8> CompressedBitmap;
FImageUtils::ThumbnailCompressImageArray(840, 720, fcolors, CompressedBitmap);


// THRID, i save it
FFileHelper::SaveArrayToFile(CompressedBitmap, *ImageFilename);

```

the file i saved seems to be broken, some parts are ok but some parts are just black.

Any ideas will be appreciated:)
have a nice day!

**Comment by getarobo** [comment]
![S_type3_20240610_195440_993](https://github.com/nicholas477/AsyncReadRT/assets/997048/0f8f7094-0ab5-493e-b331-5d2961995d9f)

this is the image i got. I feel like i am missing some settings

**Comment by getarobo** [comment]
![S_type3_20240610_195354_106](https://github.com/nicholas477/AsyncReadRT/assets/997048/5053416f-5ed1-4a87-bfe1-462c8b7715a1)
this is the image i got. I feel like i am missing some settings

**Comment by getarobo** [comment]
Although I am using RenderTexture of size 840x720, UAsyncReadEntireRTAction returns TArray<FLinearColor> of size much smaller and not consistant. Am I missing something? Thank you.

**Comment by nicholas477** [comment]
Can you share the entire cpp file?

**Comment by nicholas477** [comment]
Or add me on discord: epicgameguy
